### ISSUE TITLE
Plugin errors

### ISSUE THREAD

**Issue by N4M3Z** [PixnBits/sublime-text-npm#27]
Hello, I installed the plugin into ST3 (3083) and I am getting errors for basically all use cases. For example listing installed packages yields:
```
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text3/Build 3083/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "list in /Users/mzeman/Library/Application Support/Sublime Text 3/Installed Packages/npm.sublime-package", line 64, in run
  File "list in /Users/mzeman/Library/Application Support/Sublime Text 3/Installed Packages/npm.sublime-package", line 54, in list_and_show
TypeError: string indices must be integers
```
in the console. I am also getting a lot of these:
```
NpmRunArbitraryWorker on_close
closed view not in list
```
Is there something wrong on my end? Mac OS X, npm and node are installed via Homebrew.

**Comment by PixnBits** [comment]
```
NpmRunArbitraryWorker on_close
closed view not in list
```
are debug messages I forgot to remove :fearful: 
removed them in c98e260f2

but haven't been able to debug this yet, sorry :(
(I'll need to find a Mac that I can install Homebrew on)
